yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow, 
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('post/comment/<int:comment_id>/delete', views.comment_delete, name='comment_delete'),
    path('post/comment/<int:comment_id>/edit', views.comment_edit, name='comment_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/delete', views.post_delete, name='post_delete'),
    path('follow/', views.follow_index, name='follow_index'),    
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
  path(
    'logout/',
    LogoutView.as_view(template_name='users/logged_out.html'),
    name='logout'
  ),
  path('signup/', views.SignUp.as_view(), name='signup'),
  path(
    'login/',
    LoginView.as_view(template_name='users/login.html'),
    name='login'),
  path(
    'password_change/done/',
    PasswordChangeDoneView.as_view(
      template_name='users/password_change_done.html'
    ),
    name='password_change_done'
  ),
  path(
    'password_change/',
    PasswordChangeView.as_view(
      template_name='users/password_change_form.html'
    ),
    name='password_change'
  ),
  path(
    'reset/done/',
    PasswordResetCompleteView.as_view(
      template_name='users/password_reset_complete.html'
    ),
    name='password_reset_complete'
  ),
  path(
    'reset/<uidb64>/<token>/',
    PasswordResetConfirmView.as_view(
      template_name='users/password_reset_confirm.html'
    ),
    name='password_reset_confirm'
  ),
  path(
    'password_reset/done/',
    PasswordResetDoneView.as_view(
      template_name='users/password_reset_done.html'
    ),
    name='password_reset_done'
  ),
  path(
    'password_reset/',
    PasswordResetView.as_view(
      template_name='users/password_reset_form.html'
    ),
    name='password_reset'
  ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Наименование группы', max_length=200,)
    slug = models.SlugField('Ссылка на группу', unique=True,)
    description = models.TextField('Описание группы')

    class Meta:
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name = 'Автор публикации'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name_plural = 'Публикации'

    def __str__(self):
        return self.text[:15]

class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='comments',
        verbose_name = 'Комментарии'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name = 'Автор публикации'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария',
    )
    created = models.DateTimeField(
        'Дата комментария',
        auto_now_add=True,
    )
    
    class Meta:
        ordering = ('post',)
        verbose_name_plural = 'Комментарии'
        
    def __str__(self):
        return self.text[:15]

class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name = 'Автор публикации',
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name = 'Подписчик',
        related_name='following',
    )
    
    class Meta:
        ordering = ('author',)
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return f'{self.author}<-{self.user}'

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta():
        model = Post
        fields = ('group', 'text', 'image')
        labels = {'text': 'Текст', 'group': 'Группа'}
        help_texts = {
            'group': 'Группа, к которой будет относиться пост',
            'text': 'Текст нового поста',
        }

class CommentForm(ModelForm):
    class Meta():
        model = Comment
        fields = ('text',)
        labels = {
            # 'post': 'текст поста',
            # 'author': 'Автор комментария',
            'text': 'Текст комментария',
        }
        # help_texts = {
        #     'post': 'Текст поста',
        #     'author': 'Автор комментария',
        #     'text': 'Текст комментария',
        # }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User
from .utils import func_paginator


def index(request):
    posts_list = Post.objects.select_related('group', 'author').all()
    page_obj = func_paginator(request, posts_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts_list = group.posts.select_related('author').all()
    page_obj = func_paginator(request, posts_list)
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    person = get_object_or_404(User, username=username)
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user,
            author=person,
        ).exists()
    posts = person.posts.select_related('group').all()
    page_obj = func_paginator(request, posts)
    context = {
        'page_obj': page_obj,
        'author': person,
        'following' : following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = Post.objects.select_related('author', 'group').get(id=post_id)
    comments = post.comments.all()
    form = CommentForm()
    context = {'post': post, 'form': form, 'comments': comments}
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        instance=post,
        files=request.FILES or None
    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    form.save()
    return redirect('posts:post_detail', post.id)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    post.delete()
    return redirect('posts:profile', request.user.username)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if comment.author != request.user and request.user != comment.post.author:
        return redirect('posts:post_detail', post_id=comment.post.id)
    comment.delete()
    return redirect('posts:post_detail', post_id=comment.post.id)


@login_required
def comment_edit(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    post = comment.post
    comments = post.comments.select_related('author').all()
    if comment.author != request.user:
        return redirect('posts:post_detail', post_id=comment.post.id)
    form = CommentForm(
        request.POST or None,
        instance=comment,
    )
    if not form.is_valid():
        context = {'post': post, 'form': form, 'comments': comments}
        return render(request, 'posts/post_detail.html', context)
    form.save()
    return redirect('posts:post_detail', post_id=comment.post.id)


@login_required
def follow_index(request):
    posts_list = Post.objects.select_related(
        'author', 'group'
    ).filter(author__following__user=request.user)
    page_obj = func_paginator(request, posts_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user == author:
        return redirect('posts:profile', username)
    Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(user=request.user, author__username=username).delete()
    return redirect('posts:profile', username)

yatube/templates/includes/comments.html
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      {% if not form.instance.pk %}
        <form method="post" action="{% url 'posts:add_comment' post.id %}">
      {% else %}
        <form method="post" enctype="multipart/form-data" action="{% url 'posts:comment_edit' form.instance.pk %}">
      {% endif %}      
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
{% for comment in comments %}
  <div class="media mb-4 border rounded main-div" style="padding: 20px;">
    <div class="media-body">
      <h7 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
        <p>{{ comment.created}}</p>
      </h7>
      <hr>
      <p>
        {{ comment.text }}
      </p>
      <hr>
      {% if user == comment.author or user == post.author %}
        <a class="btn btn-outline-primary" href="{% url 'posts:comment_edit' comment.id %}">Редактировать</a>
        <a class="btn btn-outline-secondary" href="{% url 'posts:comment_delete' comment.id %}" role="button"><span style="color: red">Удалить</span></a>
      {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/footer.html
<script type="text/javascript">
  function getDate()
  {
    var date = new Date();
    var hours = date.getHours();
    var minutes = date.getMinutes();
    var seconds = date.getSeconds();
    if(seconds < 10)
    {
      seconds = '0' + seconds;
    }
    document.getElementById('timedisplay').innerHTML = hours + ':' + minutes + ':' + seconds;
    if(seconds % 2 == 0)
    {
      document.getElementById('gif').innerHTML = '-';
    } else {
      document.getElementById('gif').innerHTML = '|';
    }
  }
    setInterval(getDate, 0);
</script>
<a class="text-decoration-none" href="/about/author/">Об авторе</a>
<a> | </a>
<a class="text-decoration-none" href="/about/tech/">Технологии</a>
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
<span style="color:#007bff">
  {{ time }}
  <a id="gif"></a>
  <a id="timedisplay"></a>
</span>

yatube/templates/includes/form.html
{% load user_filters %}
{% for field in form %} 
  <div class="form-group row my-3">
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
    </label>
    {{ field|addclass:'form-control' }} 
    {% if field.help_text %}
      <small 
        id="{{ field.id_for_label }}-help"
        class="form-text text-muted"
      >
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

yatube/templates/includes/formerrors.html
{% if form.errors %}
  {% for field in form %} 
    {% for error in field.errors %}            
      <div class="alert alert-danger">
      {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/header.html
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    {% load static %}
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        {% if user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" href={% url 'posts:post_create' %}>Новая запись</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}" href={% url 'users:password_change' %}>Изменить пароль</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light" href={% url 'users:logout' %}>Выйти</a>
          </li>
          <li>
            <a class="nav-link link-light " href="{% url 'posts:profile' user.username %}"> Пользователь: {{ user.username }}</a>
          </li>
        {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" href={% url 'users:login' %}>Войти</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" href={% url 'users:signup' %}>Регистрация</a>
          </li>
        {% endif %}
      </ul>
    {% endwith %} 
  </div>
</nav>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
            </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
              <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
              <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/includes/post.html
{% load thumbnail %}
<article class="border rounded" style="padding: 15px; margin-bottom: 15px">
  <ul>
    <li>
      {% if not author %}
        Автор: {{ post.author.get_full_name }}
        <li><a href="{% url 'posts:profile' post.author %}">Все посты пользователя {{ post.author }}</a></li>
      {% else %}
        {{ post.author.get_full_name }}
      {% endif %}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    <li>
      <a href="{% url 'posts:post_detail' post.id %}">Подробная информация.</a>
    </li>
      {%if request.resolver_match.view_name != 'posts:group_posts' %}
        <li>
          {% if post.group %}
            <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
          {% else %}
            <span style="color: red">Этой публикации нет ни в одном сообществе.</span>
          {% endif %}
        </li>
      {% endif %}
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text|linebreaksbr }}</p>
</article>

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
{% with request.resolver_match.view_name as view_name %}
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link {% if view_name  == 'posts:index' %}active{% endif %}" href="/">
      {% if view_name  == 'posts:index' %}
      😏Все авторы😏
    {% else %}
      Все авторы
    {% endif %}
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if view_name  == 'posts:follow_index' %}active{% endif %}" href="/follow/">
      {% if view_name  == 'posts:follow_index' %}
      🥰Избранные авторы🥰
      {% else %}
        Избранные авторы
      {% endif %}
    </a>
  </li>
</ul>
{% endwith %}
{% endif %}