yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow, 
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('post/comment/<int:comment_id>/delete', views.comment_delete, name='comment_delete'),
    path('post/comment/<int:comment_id>/edit', views.comment_edit, name='comment_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/delete', views.post_delete, name='post_delete'),
    path('follow/', views.follow_index, name='follow_index'),    
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Наименование группы', max_length=200,)
    slug = models.SlugField('Ссылка на группу', unique=True,)
    description = models.TextField('Описание группы')

    class Meta:
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name = 'Автор публикации'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name_plural = 'Публикации'

    def __str__(self):
        return self.text[:15]

class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='comments',
        verbose_name = 'Комментарии'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name = 'Автор публикации'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария',
    )
    created = models.DateTimeField(
        'Дата комментария',
        auto_now_add=True,
    )
    
    class Meta:
        ordering = ('post',)
        verbose_name_plural = 'Комментарии'
        
    def __str__(self):
        return self.text[:15]

class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name = 'Автор публикации',
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name = 'Подписчик',
        related_name='following',
    )
    
    class Meta:
        ordering = ('author',)
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return f'{self.author}<-{self.user}'

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta():
        model = Post
        fields = ('group', 'text', 'image')
        labels = {'text': 'Текст', 'group': 'Группа'}
        help_texts = {
            'group': 'Группа, к которой будет относиться пост',
            'text': 'Текст нового поста',
        }

class CommentForm(ModelForm):
    class Meta():
        model = Comment
        fields = ('text',)
        labels = {
            # 'post': 'текст поста',
            # 'author': 'Автор комментария',
            'text': 'Текст комментария',
        }
        # help_texts = {
        #     'post': 'Текст поста',
        #     'author': 'Автор комментария',
        #     'text': 'Текст комментария',
        # }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User
from .utils import func_paginator


def index(request):
    posts_list = Post.objects.select_related('group', 'author').all()
    page_obj = func_paginator(request, posts_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts_list = group.posts.select_related('author').all()
    page_obj = func_paginator(request, posts_list)
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    person = get_object_or_404(User, username=username)
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user,
            author=person,
        ).exists()
    posts = person.posts.select_related('group').all()
    page_obj = func_paginator(request, posts)
    context = {
        'page_obj': page_obj,
        'author': person,
        'following' : following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = Post.objects.select_related('author', 'group').get(id=post_id)
    comments = post.comments.all()
    form = CommentForm()
    context = {'post': post, 'form': form, 'comments': comments}
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        instance=post,
        files=request.FILES or None
    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    form.save()
    return redirect('posts:post_detail', post.id)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    post.delete()
    return redirect('posts:profile', request.user.username)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if comment.author != request.user and request.user != comment.post.author:
        return redirect('posts:post_detail', post_id=comment.post.id)
    comment.delete()
    return redirect('posts:post_detail', post_id=comment.post.id)


@login_required
def comment_edit(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    post = comment.post
    comments = post.comments.select_related('author').all()
    if comment.author != request.user:
        return redirect('posts:post_detail', post_id=comment.post.id)
    form = CommentForm(
        request.POST or None,
        instance=comment,
    )
    if not form.is_valid():
        context = {'post': post, 'form': form, 'comments': comments}
        return render(request, 'posts/post_detail.html', context)
    form.save()
    return redirect('posts:post_detail', post_id=comment.post.id)


@login_required
def follow_index(request):
    posts_list = Post.objects.select_related(
        'author', 'group'
    ).filter(author__following__user=request.user)
    page_obj = func_paginator(request, posts_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user == author:
        return redirect('posts:profile', username)
    Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(user=request.user, author__username=username).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}{%if form.instance.pk %}Редактировать{% else %}Новый пост{% endif %}{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">{%if form.instance.pk %}Редактировать{% else %}Новый пост{% endif %}</div>
          <div class="card-body">
            {% include 'includes/formerrors.html' %}
            {% if not form.instance.pk %}
              <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
            {% else %}
              <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' form.instance.pk %}">
            {% endif %}
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  {%if form.instance.pk %}Сохранить{% else %}Добавить{% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Подписки{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Подписки</h1>
    {% include 'includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'includes/post.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{ group.title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description|linebreaksbr  }}</p>
    {% for post in page_obj %}
      {% include 'includes/post.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% load cache %}
{% cache 20 index_page %}
  <div class="container py-5">
    <h1>Это главная страница проекта Yatube</h1>
    {% include 'includes/switcher.html' %}
    <article class="border rounded" style="padding: 15px; margin-bottom: 15px">
      {% for post in page_obj %}
        {% include 'includes/post.html' %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </article>
    {% include 'includes/paginator.html' %}
  </div>
{% endcache%}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ post }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <article class="col-12 col-md-3 border rounded" style="padding: 15px">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации:
              <br>
              {{ post.pub_date|date:"d E Y" }} 
            </li>
            <li class="list-group-item">
              Группа:
              <br>
              {% if post.group %}
                {{ post.group }}
                <br>
                <a href="{% url 'posts:group_posts' post.group.slug %}">Все записи группы</a>
              {% else %}
                <span style="color: red">Этой публикации нет ни в одном сообществе.</span>
              {% endif %}
            </li>
            <li class="list-group-item">
              Автор:
              <br>
              {{ post.author.get_full_name }}
              <br>
              {{ post.author }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">Все посты пользователя</a>
            </li>
            {% if user == post.author %}
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="{% url 'posts:post_edit' post.id %}">Редактировать</a>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <a class="btn btn-primary" href="{% url 'posts:post_delete' post.id %}" role="button"><span style="color: red">Удалить</span></a>
              </li>
            {% endif %}
          </ul>
      </article>
      <article class="col-12 col-md-9 border rounded" style="padding: 15px">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text|linebreaksbr }}</p>
        {% include 'includes/comments.html' %}
      </article>
    </div> 
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}профайл пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h5>Всего постов: {{ author.posts.count }}</h5>
    <h5>Подписчиков: {{ author.following.count }}</h5>
    <h5>Подписан: {{ author.follower.count }}</h5>
      {% if user != author %}  
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
      {% endif %}
    {% for post in page_obj %}
      <p>
        {% include 'includes/post.html' %}
      </p>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %} 